# Exploratory Data Analysis (EDA) with SQL

In [19]:
# Import the necessary libraries
import pandas as pd  # For data manipulation and analysis.
import csv, sqlite3  # For working with SQLite databases.

In [20]:
# Create a connection to the database
con = sqlite3.connect("my_data1.db")
cur = con.cursor()

# Create a data frame
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

# Display the data frame first 10 rows
df.head(10)

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt
5,2013-09-29,16:00:00,F9 v1.1 B1003,VAFB SLC-4E,CASSIOPE,500,Polar LEO,MDA,Success,Uncontrolled (ocean)
6,2013-12-03,22:41:00,F9 v1.1,CCAFS LC-40,SES-8,3170,GTO,SES,Success,No attempt
7,2014-01-06,22:06:00,F9 v1.1,CCAFS LC-40,Thaicom 6,3325,GTO,Thaicom,Success,No attempt
8,2014-04-18,19:25:00,F9 v1.1,CCAFS LC-40,SpaceX CRS-3,2296,LEO (ISS),NASA (CRS),Success,Controlled (ocean)
9,2014-07-14,15:15:00,F9 v1.1,CCAFS LC-40,OG2 Mission 1 6 Orbcomm-OG2 satellites,1316,LEO,Orbcomm,Success,Controlled (ocean)

In [21]:
unique_LO = df['Landing_Outcome'].unique()
unique_LO = pd.DataFrame(unique_LO, columns=['Landing_Outcome'])
unique_LO

           Landing_Outcome
0      Failure (parachute)
1               No attempt
2     Uncontrolled (ocean)
3       Controlled (ocean)
4     Failure (drone ship)
5   Precluded (drone ship)
6     Success (ground pad)
7     Success (drone ship)
8                  Success
9                  Failure
10             No attempt

In [22]:
# Identify which columns are numerical and categorical.
df.dtypes

Date                 object
Time (UTC)           object
Booster_Version      object
Launch_Site          object
Payload              object
PAYLOAD_MASS__KG_     int64
Orbit                object
Customer             object
Mission_Outcome      object
Landing_Outcome      object
dtype: object

In [23]:
# Filter the data frame for the launch sites with the booster version, and payload mass.
df[['Booster_Version', 'Launch_Site', 'PAYLOAD_MASS__KG_']]

    Booster_Version   Launch_Site  PAYLOAD_MASS__KG_
0    F9 v1.0  B0003   CCAFS LC-40                  0
1    F9 v1.0  B0004   CCAFS LC-40                  0
2    F9 v1.0  B0005   CCAFS LC-40                525
3    F9 v1.0  B0006   CCAFS LC-40                500
4    F9 v1.0  B0007   CCAFS LC-40                677
..              ...           ...                ...
96     F9 B5B1062.1  CCAFS SLC-40               4311
97    F9 B5B1061.1     KSC LC-39A              12500
98     F9 B5B1063.1   VAFB SLC-4E               1192
99   F9 B5 B1049.7   CCAFS SLC-40              15600
100  F9 B5 B1058.4     KSC LC-39A               2972

[101 rows x 3 columns]

In [24]:
# Remove blank rows from table if exists
%sql DROP TABLE IF EXISTS SPACEXTABLE;

# Create a table with the data from the SPACEXTBL table
%sql create table SPACEXTABLE as select * from SPACEXTBL where Date is not null

 * sqlite:///my_data1.db
Done.
 * sqlite:///my_data1.db
Done.

[]

### EDA with SQL

In [25]:
# Display the names of the unique launch sites  in the space mission
launch_site = cur.execute('SELECT DISTINCT Launch_Site FROM(SPACEXTABLE);')
pd.DataFrame(launch_site.fetchall(), columns=[x[0] for x in launch_site.description])

    Launch_Site
0   CCAFS LC-40
1   VAFB SLC-4E
2    KSC LC-39A
3  CCAFS SLC-40

In [26]:
# Display 5 records where launch sites begin with the string 'CCA' 
CCA_launch_sites = cur.execute("SELECT * FROM SPACEXTABLE WHERE Launch_Site LIKE 'CCA%' LIMIT 5;")

results = cur.fetchall()
for row in results:
    print(row)

('2010-06-04', '18:45:00', 'F9 v1.0  B0003', 'CCAFS LC-40', 'Dragon Spacecraft Qualification Unit', 0, 'LEO', 'SpaceX', 'Success', 'Failure (parachute)')
('2010-12-08', '15:43:00', 'F9 v1.0  B0004', 'CCAFS LC-40', 'Dragon demo flight C1, two CubeSats, barrel of Brouere cheese', 0, 'LEO (ISS)', 'NASA (COTS) NRO', 'Success', 'Failure (parachute)')
('2012-05-22', '7:44:00', 'F9 v1.0  B0005', 'CCAFS LC-40', 'Dragon demo flight C2', 525, 'LEO (ISS)', 'NASA (COTS)', 'Success', 'No attempt')
('2012-10-08', '0:35:00', 'F9 v1.0  B0006', 'CCAFS LC-40', 'SpaceX CRS-1', 500, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'No attempt')
('2013-03-01', '15:10:00', 'F9 v1.0  B0007', 'CCAFS LC-40', 'SpaceX CRS-2', 677, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'No attempt')

In [27]:
# Display the total payload mass carried by boosters launched by NASA (CRS)

#  Total Payload Mass
cur.execute('SELECT SUM(PAYLOAD_MASS__KG_) AS TOTAL_PMK FROM SPACEXTABLE;')
results = cur.fetchone()
TOTAL_PMK = results[0]

# Quantity of Unique Payload Mass's
payload_mass = cur.execute('SELECT DISTINCT PAYLOAD_MASS__KG_ FROM SPACEXTABLE;')
payload_mass = pd.DataFrame(payload_mass)

# Display Results
print('Total Payload Mass:', TOTAL_PMK)
print('Quantity of Unique Values:', payload_mass.nunique())

# Display the first 10 rows of the payload mass
payload_mass.head(10)

Total Payload Mass: 619967
Quantity of Unique Values: 0    78
dtype: int64

      0
0     0
1   525
2   500
3   677
4  3170
5  3325
6  2296
7  1316
8  4535
9  4428

In [28]:
# TOTAL PAYLOAD MASS OF NASA
total_plm_nasa = cur.execute('SELECT SUM(PAYLOAD_MASS__KG_) AS TOTAL_PMK FROM SPACEXTABLE WHERE CUSTOMER LIKE "NASA%";')
results = cur.fetchone()
total_plm = pd.DataFrame([results], columns=['Total payload carried by boosters from NASA'])
total_plm

   Total payload carried by boosters from NASA
0                                        99980

In [29]:
# average payload mass by f9 v1.1
F9_v11_Mean = cur.execute('SELECT AVG(PAYLOAD_MASS__KG_) FROM SPACEXTABLE WHERE Booster_Version = "F9 v1.1";')
F9_v11 = pd.DataFrame([F9_v11_Mean.fetchone()], columns=['Average Payload Mass by F9 v1.1'])
F9_v11

   Average Payload Mass by F9 v1.1
0                           2928.4

In [30]:
# List the date when the first successful landing outcome in ground pad was achieved.
success_landing = cur.execute('SELECT MIN(Date) FROM SPACEXTABLE WHERE Landing_Outcome = "Success (ground pad)";')

# Pandas DataFrame
fist_success_landing = pd.DataFrame([success_landing.fetchone()], columns=['First Successful Ground Landing Date'])
fist_success_landing

  First Successful Ground Landing Date
0                           2015-12-22

In [31]:
# List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000
successful_busters = cur.execute('SELECT * FROM SPACEXTABLE WHERE Landing_Outcome =  "Success (drone ship)" AND PAYLOAD_MASS__KG_ BETWEEN 4000 AND 6000;')

# Fetch the column names from the cursor description
columns = [description[0] for description in successful_busters.description]

# Display the Results
success_landing = pd.DataFrame(successful_busters.fetchall(), columns=columns)
success_landing

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2016-05-06,5:21:00,F9 FT B1022,CCAFS LC-40,JCSAT-14,4696,GTO,SKY Perfect JSAT Group,Success,Success (drone ship)
1,2016-08-14,5:26:00,F9 FT B1026,CCAFS LC-40,JCSAT-16,4600,GTO,SKY Perfect JSAT Group,Success,Success (drone ship)
2,2017-03-30,22:27:00,F9 FT B1021.2,KSC LC-39A,SES-10,5300,GTO,SES,Success,Success (drone ship)
3,2017-10-11,22:53:00,F9 FT B1031.2,KSC LC-39A,SES-11 / EchoStar 105,5200,GTO,SES EchoStar,Success,Success (drone ship)

In [32]:
# List the total number of successful and failure mission outcomes 
total_landing_success = cur.execute('SELECT Landing_Outcome, COUNT(*) FROM SPACEXTABLE GROUP BY Landing_Outcome;')

# Display the Results
total_landing_success = pd.DataFrame(total_landing_success, columns=['Landing Outcome', 'Total'])
total_landing_success

           Landing Outcome  Total
0       Controlled (ocean)      5
1                  Failure      3
2     Failure (drone ship)      5
3      Failure (parachute)      2
4               No attempt     21
5              No attempt       1
6   Precluded (drone ship)      1
7                  Success     38
8     Success (drone ship)     14
9     Success (ground pad)      9
10    Uncontrolled (ocean)      2

In [33]:
# List the   names of the booster_versions which have carried the maximum payload mass. Use a subquery
boosterVersion_maxPayload = cur.execute('SELECT Booster_Version, PAYLOAD_MASS__KG_ FROM SPACEXTABLE WHERE PAYLOAD_MASS__KG_ = (SELECT MAX (PAYLOAD_MASS__KG_) FROM SPACEXTABLE);')

# PAndas DataFrame
boosterVersion_maxPayload = pd.DataFrame(boosterVersion_maxPayload, columns=['Booster Version', 'Payload Mass'])
boosterVersion_maxPayload

   Booster Version  Payload Mass
0    F9 B5 B1048.4         15600
1    F9 B5 B1049.4         15600
2    F9 B5 B1051.3         15600
3    F9 B5 B1056.4         15600
4    F9 B5 B1048.5         15600
5    F9 B5 B1051.4         15600
6    F9 B5 B1049.5         15600
7   F9 B5 B1060.2          15600
8   F9 B5 B1058.3          15600
9    F9 B5 B1051.6         15600
10   F9 B5 B1060.3         15600
11  F9 B5 B1049.7          15600

In [34]:
# List the records which will display the month names, failure landing_outcomes in drone ship,
# booster versions, launch_site for the months in year 2015.
failure_DroneShip = cur.execute(' SELECT * FROM SPACEXTABLE WHERE Landing_Outcome = "Failure (drone ship)" AND substr(Date, 6,2) AND substr(Date, 0,5)="2015";')

# Pandas DataFrame
failure_DroneShip = pd.DataFrame(failure_DroneShip, columns=[description[0] for description in failure_DroneShip.description])
failure_DroneShip

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2015-01-10,9:47:00,F9 v1.1 B1012,CCAFS LC-40,SpaceX CRS-5,2395,LEO (ISS),NASA (CRS),Success,Failure (drone ship)
1,2015-04-14,20:10:00,F9 v1.1 B1015,CCAFS LC-40,SpaceX CRS-6,1898,LEO (ISS),NASA (CRS),Success,Failure (drone ship)

In [35]:
# Rank the count of landing outcomes (such as Failure (drone ship) or 
# Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order.
landing_outcomes = cur.execute('SELECT Landing_Outcome, COUNT(*) as outcome_count  FROM SPACEXTABLE WHERE Date BETWEEN "2010-06-04" and "2017-03-30" GROUP BY Landing_Outcome ORDER BY outcome_count DESC;')

# Pandas DataFrame
landing_outcomes = pd.DataFrame(landing_outcomes, columns=[description[0] for description in landing_outcomes.description])
landing_outcomes

          Landing_Outcome  outcome_count
0              No attempt             10
1    Success (drone ship)              6
2    Failure (drone ship)              5
3    Success (ground pad)              3
4      Controlled (ocean)              3
5    Uncontrolled (ocean)              2
6     Failure (parachute)              2
7  Precluded (drone ship)              1

This Jupyter Notebook was Completed By [Jonathan Scott](http://www.linkedin.com/in/jonathan-scott-140709317) as part of the IBM Data Science Certification.

## Author

Lakshmi Holla

## Other Contributors

Rav Ahuja

#### © IBM Corporation 2021. All rights reserved.